var features = [
    {
      zipcode: '60620',
      newspaper:  'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60624',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60654',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60604',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
    }, {
      zipcode: '60622',
      newspaper: 'z',
      city: 'z',
      date: 'z',
      headline: 'z',
      author: 'z',
      url: 'z'
   }
  ];